# Generated by Django 5.2.17 on 2026-08-16 00:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='frontiernode',
            name='frontier_node_unique',
        ),
        migrations.RemoveIndex(
            model_name='adminunit',
            name='radar_admin_level_f26085_idx',
        ),
        migrations.RemoveIndex(
            model_name='frontiernode',
            name='radar_front_event_i_6399be_idx',
        ),
        migrations.RemoveIndex(
            model_name='outreach',
            name='radar_outre_status_486416_idx',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='is_organization',
        ),
        migrations.RemoveField(
            model_name='event',
            name='budget_usd',
        ),
        migrations.RemoveField(
            model_name='frontiernode',
            name='avg_cost_usd',
        ),
        migrations.RemoveField(
            model_name='frontiernode',
            name='cadence_minutes',
        ),
        migrations.RemoveField(
            model_name='frontiernode',
            name='freshness',
        ),
        migrations.RemoveField(
            model_name='frontiernode',
            name='ring',
        ),
        migrations.RemoveField(
            model_name='frontiernode',
            name='score',
        ),
        migrations.RemoveField(
            model_name='frontiernode',
            name='total_cost_usd',
        ),
        migrations.RemoveField(
            model_name='harvestjob',
            name='budget_usd',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='automatic',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='error',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='adminunit',
            name='country_code',
            field=models.CharField(db_index=True, default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminunit',
            name='geonames_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='payment_network',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='country_code',
            field=models.CharField(db_index=True, default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='frontiernode',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontier_nodes', to='radar.actor'),
        ),
        migrations.AddField(
            model_name='frontiernode',
            name='observed_cost_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='harvestjob',
            name='target_kind',
            field=models.CharField(choices=[('search', 'Keyword search over a place'), ('profile', "One account's timeline"), ('thread', 'Replies under one post'), ('comments', 'Comments on one post')], default='search', max_length=20),
        ),
        migrations.AddField(
            model_name='outreach',
            name='about_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach', to='radar.requirement'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_outreach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outreach',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_replies', to='radar.observation'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='purpose',
            field=models.CharField(choices=[('connect', 'Introduce a need to an offer'), ('answer', 'Answer someone who asked where to go or how to help'), ('verify', 'Confirm a need or offer is still live'), ('request_detail', 'Ask for the location or contact the post omitted')], default='connect', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outreach',
            name='target_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='level',
            field=models.CharField(choices=[('country', 'Country'), ('admin_1', 'First level (state, department, province)'), ('admin_2', 'Second level (municipality, county, district)'), ('admin_3', 'Third level (settlement, locality, ward)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='name_norm',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='kind',
            field=models.CharField(choices=[('handle', 'Platform handle'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('website', 'Website'), ('form', 'Web form'), ('payment', 'Payment account'), ('street_address', 'Street address')], max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='spent_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='frontiernode',
            name='admin_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frontier_nodes', to='radar.adminunit'),
        ),
        migrations.AlterField(
            model_name='frontiernode',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('exhausted', 'Exhausted — produced nothing useful'), ('paused', 'Paused')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='frontiernode',
            name='yield_rate',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='frontiernode',
            name='zone',
            field=models.CharField(choices=[('impact', 'Impact zone — search for demand'), ('support', 'Support zone — search for supply')], max_length=10),
        ),
        migrations.AlterField(
            model_name='harvestjob',
            name='decided_by',
            field=models.CharField(choices=[('agent', 'Frontier agent'), ('rule', 'Scheduling rule'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='precision',
            field=models.CharField(choices=[('country', 'Country'), ('admin_1', 'First level'), ('admin_2', 'Second level'), ('admin_3', 'Third level'), ('neighborhood', 'Neighborhood or rural district'), ('street_address', 'Street address'), ('exact_point', 'Exact point')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='source',
            field=models.CharField(choices=[('google', 'Google Geocoding'), ('gazetteer', 'Administrative gazetteer (GeoNames)'), ('platform', 'Platform metadata'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('comment_reply', 'Reply to a post or comment'), ('direct_message', 'Direct message'), ('phone_call', 'Phone call')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('draft', 'Drafted, waiting for a human'), ('dispatched', 'A human opened the link and sent it'), ('answered', 'The recipient replied'), ('dismissed', 'A human decided not to send it'), ('failed', 'Could not be delivered')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminunit',
            index=models.Index(fields=['country_code', 'level', 'name_norm'], name='radar_admin_country_d74d74_idx'),
        ),
        migrations.AddIndex(
            model_name='frontiernode',
            index=models.Index(fields=['event', 'status', '-yield_rate'], name='radar_front_event_i_5ecc01_idx'),
        ),
        migrations.AddIndex(
            model_name='outreach',
            index=models.Index(fields=['status', 'purpose', 'created_at'], name='radar_outre_status_f1bb98_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminunit',
            constraint=models.UniqueConstraint(fields=('country_code', 'level', 'code'), name='admin_unit_unique'),
        ),
        migrations.AddConstraint(
            model_name='frontiernode',
            constraint=models.UniqueConstraint(condition=models.Q(('actor__isnull', True)), fields=('event', 'admin_unit', 'platform'), name='frontier_place_unique'),
        ),
        migrations.AddConstraint(
            model_name='frontiernode',
            constraint=models.UniqueConstraint(condition=models.Q(('admin_unit__isnull', True)), fields=('event', 'actor', 'platform'), name='frontier_account_unique'),
        ),
        migrations.AddConstraint(
            model_name='frontiernode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('admin_unit__isnull', False)), models.Q(('actor__isnull', False), ('admin_unit__isnull', True)), _connector='OR'), name='frontier_node_watches_exactly_one'),
        ),
    ]
