# Generated by Django 5.2.17 on 2026-08-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_remove_frontiernode_frontier_node_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='author_avatar_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
