# Generated by Django 5.2.17 on 2026-08-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_alter_observation_author_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='classification',
            field=models.CharField(choices=[('need', 'Need'), ('offer', 'Offer'), ('both', 'Need and offer'), ('discard', 'Discard')], max_length=20),
        ),
    ]
