# Generated by Django 5.2.17 on 2026-08-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_alter_extraction_classification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='location_unique',
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('text_norm', 'admin_unit'), name='location_unique', nulls_distinct=False),
        ),
    ]
