# Generated by Django 5.2.17 on 2026-08-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0006_remove_location_location_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_snapshot', to='radar.event')),
            ],
        ),
    ]
