# Generated by Django 5.2.17 on 2026-08-16 06:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0007_graphsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='alternate_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=60), blank=True, default=list, size=None),
        ),
    ]
