# Generated by Django 5.2.17 on 2026-08-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0008_resourcetype_alternate_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphsnapshot',
            name='stale',
            field=models.BooleanField(default=False),
        ),
    ]
